//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotel()
        {
            this.ListOfChanges = new HashSet<ListOfChanges>();
            this.photosOfHotels = new HashSet<photosOfHotels>();
            this.TypeOfRoom = new HashSet<TypeOfRoom>();
        }
    
        public int id { get; set; }
        public string nameOfHotel { get; set; }
        public int idOfCity { get; set; }
        public string address { get; set; }
        public string phoneNumber { get; set; }
        public string hotelDescription { get; set; }
        public int countOfStars { get; set; }
        public byte[] ImagePreview { get; set; }
        public Nullable<int> idListOfChanges { get; set; }
    
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListOfChanges> ListOfChanges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<photosOfHotels> photosOfHotels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TypeOfRoom> TypeOfRoom { get; set; }
    }
}
