//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListOfChanges
    {
        public int id { get; set; }
        public int idOfAdministrator { get; set; }
        public string typeOfChange { get; set; }
    
        public virtual Administrator Administrator { get; set; }
        public virtual Hotel Hotel { get; set; }
    }
}
